const ERROR_CODES = {
	USERNAME_IN_USE: 'USERNAME_IN_USE',
	EMAIL_IN_USE: 'EMAIL_IN_USE',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	USERNAME_INVALID: 'USERNAME_INVALID',
	EMAIL_INVALID: 'EMAIL_INVALID',
	PASSWORD_INVALID: 'PASSWORD_INVALID',
	LOCALE_INVALID: 'LOCALE_INVALID',
	NOT_ALLOWED: 'NOT_ALLOWED',
	CONFLICT: 'CONFLICT',
	INVALID: 'INVALID'
};

module.exports = ERROR_CODES;
