const bar = require('./bar');
const help = require('./help');
const { Functions } = require('@cedalo/parser');

const {
	ATTRIBUTES,
	CLASSIFYPOINT,
	EVENTS,
	FILLLINEARGRADIENT,
	FILLPATTERN,
	FILLVIDEO,
	FILLRADIALGRADIENT,
	FONTFORMAT,
	LINEFORMAT,
	SERIES,
	SERIESTIME,
	AXIS,
	ONCLICK,
	ONDOUBLECLICK,
	ONMOUSEDOWN,
	ONMOUSEUP,
	ONVALUECHANGE,
	QRCODE
} = Functions;

module.exports = {
	help,
	functions: {
		ATTRIBUTES,
		BAR: bar,
		CLASSIFYPOINT,
		'DRAW.BUTTON': Functions['DRAW.BUTTON'],
		'DRAW.CHECKBOX': Functions['DRAW.CHECKBOX'],
		'DRAW.ELLIPSE': Functions['DRAW.ELLIPSE'],
		'DRAW.LABEL': Functions['DRAW.LABEL'],
		'DRAW.LINE': Functions['DRAW.LINE'],
		'DRAW.KNOB': Functions['DRAW.KNOB'],
		'DRAW.PLOT': Functions['DRAW.PLOT'],
		'DRAW.STREAMCHART': Functions['DRAW.STREAMCHART'],
		'DRAW.POLYGON': Functions['DRAW.POLYGON'],
		'DRAW.RECTANGLE': Functions['DRAW.RECTANGLE'],
		'DRAW.SLIDER': Functions['DRAW.SLIDER'],
		EVENTS,
		FILLLINEARGRADIENT,
		FILLPATTERN,
		FILLVIDEO,
		FILLRADIALGRADIENT,
		FONTFORMAT,
		LINEFORMAT,
		SERIES,
		SERIESTIME,
		AXIS,
		ONCLICK,
		ONDOUBLECLICK,
		ONMOUSEDOWN,
		ONMOUSEUP,
		ONVALUECHANGE,
		QRCODE
	}
};
