const ErrorCodes = {
	MACHINE_SERVER_NOT_CONNECTED: 'MACHINE_SERVER_NOT_CONNECTED',
	GRAPH_SERVER_NOT_CONNECTED: 'GRAPH_SERVER_NOT_CONNECTED',
	MACHINE_SERVER_AND_GRAPH_SERVER_NOT_CONNECTED:
		'MACHINE_SERVER_AND_GRAPH_SERVER_NOT_CONNECTED'
};

module.exports = ErrorCodes;
