./scripts/deploy.js \
  --tag 1.2-rpi \
  --derivative personal \
  --image arm32v6/node:12.4.0-alpine \
  --service @cedalo/service-machines \
  --service @cedalo/service-auth \
  --service @cedalo/service-streams \
  --service @cedalo/service-graphs \
  --service @cedalo/service-opcua \
  --service @cedalo/gateway \
  --service @cedalo/webui \
  --push
